### ISSUE TITLE
Add the ability to use tags to create tests

### ISSUE THREAD

**Issue by PGG106** [AndyGrant/OpenBench#126]
As per title, add the ability to use tags in place of branch names when creating tests, Current behaviour seems to be interpreting the tag as a branch name. Confirmed not working on current master and several old version.

**Comment by AndyGrant** [comment]
Resolved via https://github.com/AndyGrant/OpenBench/commit/a9c532f8736d56a9f7edbdabb5f4feaa659f812f

OpenBench will assume that non-sha values are branch names. If the commit is not found by looking up as a branch, it will attempt to look up the name as a tag instead. In the event of the tag having the same name as a branch, the branch will be returned. 

Support for private instances with tags is unknown.

**Comment by AndyGrant** [comment]
Confirmed to be working for private sourced engines.
