### ISSUE TITLE
Prefix worker binaries with engine name

### ISSUE THREAD

**Issue by noobpwnftw** [AndyGrant/OpenBench#18]
It's now hard to tell if any engines are left over and running in background.

**Comment by AndyGrant** [comment]
Even cute chess has some issues killing the engines it spawns. Your are
only seeing this when you kill the machines right? Not when a workload is
finished normally...?

**Comment by noobpwnftw** [comment]
Scenarios may include workers report their results and found task ended, not that I want to randomly kill things.

Engines should also detect stdout closed when cutechess exited but failed to terminate them.
