### ISSUE TITLE
Exception: Unable to retrieve .zip archive from Github

### ISSUE THREAD

**Issue by MrStark7797** [AndyGrant/OpenBench#185]
Exception: Unable to retrieve .zip archive from Github

**Comment by AndyGrant** [comment]
I'll need more information than that to be able to provide any insight unfortunately. The stack trace would help narrow it down, as the Worker will pull books, and engines, from github.

**Comment by MrStark7797** [comment]
I do have an image:

![image.png](https://github.com/AndyGrant/OpenBench/assets/114497071/184ee99b-587a-4aca-9abf-d0034b12a48b)

Now I'm not sure why this is the case as I have tried changing client_repo_url from your main branch and my fork.

This is in context of initialising a client to perform open bench.

Sorry for being ambiguous,

Thanks!

**Comment by AndyGrant** [comment]
Can you add a print statement after this line:
https://github.com/MrStark7797/OpenBench/blob/master/Client/client.py#L106

Printing the version_ref, ie the json version of the response? I'm guessing that your client failed to reach the server in some way, which explains why the response is not as expected.

**Comment by AndyGrant** [comment]
Also, while running that to produce the output, please capture the log output of your server. There should be a successful request made to /clientVersionRef/.
