### ISSUE TITLE
Laser engine keeps running when cutechess ended

### ISSUE THREAD

**Issue by noobpwnftw** [AndyGrant/OpenBench#19]
Happening on your 30-core worker too.

**Comment by AndyGrant** [comment]
Are you saying that you checked the hashses, and found that the repeated processes where just from the 1 laser test many hours ago?

**Comment by noobpwnftw** [comment]
Yes, correct. It's happening on your 30-core machine as of now.

**Comment by AndyGrant** [comment]
Okay -- know I understand your prefix issue. I'm looking now, but I'm confused as to why this happens.

**Comment by AndyGrant** [comment]
So I cannot repeat the issue on my Windows box. On one Linux box,  I can. Cutechess kills 50% of the machines, which makes me think Jeffrey does not respect quit/stop during search. Looking there next :)
