### ISSUE TITLE
Switching presets doesn't account for default settings

### ISSUE THREAD

**Issue by codedeliveryservice** [AndyGrant/OpenBench#196]
When switching between presets, it appears to only consider the settings of the new preset. Consequently, if the new one lacks certain settings, it retains values from the previous config instead of falling back to defaults.

![](https://github.com/AndyGrant/OpenBench/assets/93079612/1f85a279-f38b-4fc6-9cb2-313b7a18b431)

**Comment by AndyGrant** [comment]
Merged https://github.com/AndyGrant/OpenBench/commit/989305997bcfa866c5a0fce554d2ece586f378c8
