### ISSUE TITLE
Proper HTTP request timeout

### ISSUE THREAD

**Issue by noobpwnftw** [AndyGrant/OpenBench#21]
Default behavior of requests.get is never, causing worker hanging.

**Comment by AndyGrant** [comment]
Read docs, easy fix. Will do when I get home after July 4th activities.

**Comment by AndyGrant** [comment]
How long would you like (in seconds) for the timeout ?

**Comment by AndyGrant** [comment]
Resolved https://github.com/AndyGrant/OpenBench/commit/2e82ea8e9274887568ec7cced074bf6f860ebc12
