### ISSUE TITLE
Allow connections via HTTPS

### ISSUE THREAD

**Issue by laldon** [AndyGrant/OpenBench#26]
It's 2018 duuude.

> requests.exceptions.ConnectionError: HTTPSConnectionPool(host='chess.grantnet.us', port=443):
Max retries exceeded with url: /getFiles/
(Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000006703F5FA90>:
Failed to establish a new connection:
[WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))

**Comment by AndyGrant** [comment]
This is not an OpenBench thing, but instead a webserver thing.
