### ISSUE TITLE
Name builds accordingly

### ISSUE THREAD

**Issue by laldon** [AndyGrant/OpenBench#27]
It'd be nice if you could add the suffixes _base and _dev for the associated builds so one can understand what's going on:

> Started game 6 of 250 (Ethereal 10.86 (POPCNT) vs Ethereal 10.86 (POPCNT))
Finished game 6 (Ethereal 10.86 (POPCNT) vs Ethereal 10.86 (POPCNT)): 1-0 {White wins by adjudication}

**Comment by AndyGrant** [comment]
I can easily just make it ``test vs base``

**Comment by AndyGrant** [comment]
https://github.com/AndyGrant/OpenBench/commit/ae594a71b3e2a018b7912784b1eca4452c1c2305 resolved
