### ISSUE TITLE
Create tests with tags

### ISSUE THREAD

**Issue by ratosh** [AndyGrant/OpenBench#28]
I've added this option on my fork, just looks for a tag if the branch is not found.
[Changes](https://github.com/ratosh/OpenBench/commit/9fc5a1777ea92a1209898f8eaee4163b3eb58e8b)

**Comment by ratosh** [comment]
Yes, testing with a specific tag makes no sense since it would pass/fail sprt really fast but if i run the test using a specific number of games i can check the progression within a error window. 

So I've also added a min games option. As it pass/fail fast it would just play the minimum number of games i set.

I'm using it to run master vs latest release in Openbench and check the master progress. With this information i decide if it is strong enough to become a release (currently releasing when it reaches 100 self play elo).

**Comment by AndyGrant** [comment]
I've sorta resolved this with https://github.com/AndyGrant/OpenBench/commit/63091838389c7c6a60050c0d92bb886c3a2d3e03 , which allows creation using the SHA of a commit.

I see that you have updated you have been trying to keep some things updated from OpenBench in your own fork. Any issues? I've forgotten/lost your contact info and the link to your framework (if its still on the web).

**Comment by ratosh** [comment]
Nice! My instance is running fine, but only available on my LAN.
