### ISSUE TITLE
Issue with Django profil

### ISSUE THREAD

**Issue by tryingsomestuff** [AndyGrant/OpenBench#34]
Trying to set up my own instance for Minic I'm running on this issue as soon as I try to login with the superadmin account

```
Django Version: | 2.0.6
DoesNotExist
Profile matching query does not exist.
/home/vivien/.local/lib/python3.7/site-packages/django/db/models/query.py in get, line 403
/usr/bin/python3
3.7.5
```
Does that ring a bell ?

**Comment by AndyGrant** [comment]
The superadmin account made via the command line is not an actual OpenBench "user". But that account can be used to log into the admin page http://chess.grantnet.us/admin/ (change to localhost for you probably). 

IE, you create a superadmin Root via the command line. Then via the website you register yourself a new user, Minic. You can then login to the admin page as Root and set the permissions for Minic (Enable, Approve, Superuser, ..., )

**Comment by tryingsomestuff** [comment]
ok got it. But then I run into this when changing the created account privilege

```
Exception Type: | OperationalError
no such table: main.auth_permission__old
/home/vivien/.local/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py in execute, line 303
/usr/bin/python3
3.7.5
```

**Comment by tryingsomestuff** [comment]
Related to this : https://stackoverflow.com/questions/53637182/django-no-such-table-main-auth-user-old

**Comment by tryingsomestuff** [comment]
Solved upgrading django to 2.2.7

**Comment by AndyGrant** [comment]
Yeah I was taking a look at that as well. I'm not sure exactly what to recommend, as I don't have the issue locally on either of my machines, nor do I have it on the machine that hosts chess.grantnet.us

Its possible that by going to the latest version, new issues could arise. I'm not sure how well the Django project maintains backwards compatibility. I will try tinkering around with 2.2.7 locally if I can. Sorry for the issues.

**Comment by tryingsomestuff** [comment]
Maybe just update the readme to recommend a higher version of Django.
