### ISSUE TITLE
Qt 4 dependancy ?

### ISSUE THREAD

**Issue by lucasart** [AndyGrant/OpenBench#39]
When running the `OpenBench.py` client, it downloads the cutechess (linux) executable, and running it throws this error:
```
./cutechess: error while loading shared libraries: libQtCore.so.4: cannot open shared object file: No such file or directory
```
It's the cutechess executable hat fails to run on my machine. But my cutechess-cli (which I compiled from source using Qt5) works fine. Are you using a (very) old version that is based on Qt4 ?

PS: For now, I'll just hack the python client to make it use my own cutechess-cli.

**Comment by lucasart** [comment]
The annoying thing with Qt is that it does not allow production of self-sufficient executable. There is always a Qt runtime "DLL", even in the Linux case. And, of course, my Qt runtime is going to be a differnet version from yours, so to make things robust, I'm afraid you may have to replicate the Windows DLL logic to Linux here with `libQtCore.so.4`.

**Comment by lucasart** [comment]
Looks like we're in business:

ID | User | System | Updated | Workload | Threads | MNPS
-- | -- | -- | -- | -- | -- | --
1399 | Andrew | Linux 4.16.0-041600-generic | 2019-11-20 13:29 | AspiIncreaseByDepth | 32 | 1.27
1535 | WorkerPool | Linux 3.10.0-1062.4.1.el7.x86_64 | 2019-11-20 13:29 | AspiIncreaseByDepth | 16 | 1.37
1536 | WorkerPool | Linux 3.10.0-1062.4.1.el7.x86_64 | 2019-11-20 13:28 | AspiIncreaseByDepth | 16 | 1.37
1537 | WorkerPool | Linux 3.10.0-1062.4.1.el7.x86_64 | 2019-11-20 13:29 | AspiIncreaseByDepth | 16 | 1.37
1538 | WorkerPool | Linux 3.10.0-1062.4.1.el7.x86_64 | 2019-11-20 13:28 | AspiIncreaseByDepth | 16 | 1.37
1539 | WorkerPool | Linux 3.10.0-1062.4.1.el7.x86_64 | 2019-11-20 13:29 | AspiIncreaseByDepth | 16 | 1.38
1540 | WorkerPool | Linux 3.10.0-1062.4.1.el7.x86_64 | 2019-11-20 13:29 | AspiIncreaseByDepth | 16 | 1.38
1541 | WorkerPool | Linux 3.10.0-1062.4.1.el7.x86_64 | 2019-11-20 13:28 | AspiIncreaseByDepth | 16 | 1.37
1542 | WorkerPool | Linux 3.10.0-1062.4.1.el7.x86_64 | 2019-11-20 13:29 | AspiIncreaseByDepth | 16 | 1.37
1544 | WorkerPool | Linux 3.10.0-1062.4.1.el7.x86_64 | 2019-11-20 13:29 | AspiIncreaseByDepth | 16 | 1.38
1548 | lucasart | Linux 5.3.11-arch1-1 | 2019-11-20 13:29 | AspiIncreaseByDepth | 7 | 1.54

**Comment by AndyGrant** [comment]
The worker already downloads ``libcutechess.so.1``. This is a very old (stable) version of cutechess, and likely is using Qt4. Are you suggesting I kick everything up to Qt5, or that I also have the workers pull down ``libcutechess.so.4``, or something else entirely?

**Comment by lucasart** [comment]
No, you're confusing 2 unrelated libs:
* libQtcore is the runtime library that *any* application compiled with Qt4 needs. That's what you're missing.
* libcutechess is pure cutechess related (it is a lib shared between GUI and CLI that does chess related stuff).

**Comment by ppigazzini** [comment]
> There is always a Qt runtime "DLL", even in the Linux case.

@lucasart use the [build scripts](https://github.com/glinscott/fishtest/wiki/Build-cutechess-with-Qt5-static) on fishtest wiki to make a cutechess-cli linux QT5 static build and a Windows static build.
Or take the lazy road and download the up-to-date cutechess-cli binaries from https://github.com/official-stockfish/books

Nice project @AndyGrant :)

**Comment by AndyGrant** [comment]
On hold until https://github.com/cutechess/cutechess/issues/616 is merged and resolved. Will be looking to do this soon, as the FRC false flags are an issue.

**Comment by AndyGrant** [comment]
I'm not waiting any longer -- I don't like seeing errors. Resolved for Linux via https://github.com/AndyGrant/OpenBench/commit/2f67084d2e32608b332c3a6a281470eccf43b40e and https://github.com/AndyGrant/OpenBench/commit/8eea4ec4d4b3d6595a1d1f0637df8278c9d75389 

Windows has always been Qt5, but I still need to update those. That will be a new issue.
