### ISSUE TITLE
Support for Demolito

### ISSUE THREAD

**Issue by AndyGrant** [AndyGrant/OpenBench#40]
@lucasart , what time controls and hash settings would you like for Demolito's STC/LTC/SMP testing? Here is the template for Ethereal/Laser

```
'testmodes' : {
    'stc'     : { 'threads' : 1, 'hash' :   8, 'timecontrol' : '10.0+0.1' },
    'ltc'     : { 'threads' : 1, 'hash' :  64, 'timecontrol' : '60.0+0.6' },
    'smpstc'  : { 'threads' : 8, 'hash' :  64, 'timecontrol' : '5.0+0.05' },
    'smpltc'  : { 'threads' : 8, 'hash' : 256, 'timecontrol' : '20.0+0.2' },
},
```

**Comment by lucasart** [comment]
Please use the following, which should be a good compromise between resource usage and tc scaling risk:

stc: 1, 8, 8+0.08
ltc: 1, 32, 32+0.32
smpstc: 8, 32, 4+0.04
smpltc: 8, 128, 16+0.16

**Comment by lucasart** [comment]
I was looking at the 'nps' values in OpenBench/config.py, used for tc scaling by the client.

The Demolito one looks correct. I just need to figure out how to regain the 8% speed loss from using gcc instead of clang, and it will be as fast as Ethereal.

But the Weiss one looks really high. Is it really 2.67x faster than Ethereal ?

**Comment by AndyGrant** [comment]
Updated to match your request here https://github.com/AndyGrant/OpenBench/commit/018ecd526ee97e18e35d1c0deb7d2ad0de340437

Yes, Weiss really is that much faster. Weiss is very early in development. I will have to update that NPS value over time, where as for Ethereal and Demolito (and Laser), the value will be fairly stable.

**Comment by AndyGrant** [comment]
Pulling down that change to the server now (forgot to earlier, hence your current test defaulting to 10s). That test seems fine on my machine from viewing the logs, and fine from your machines reported results. I'm going to close this issue, as I believe we've got support.
