### ISSUE TITLE
Dynamic GAMES_PER_THREAD

### ISSUE THREAD

**Issue by lucasart** [AndyGrant/OpenBench#42]
Proposal: replace `GAMES_PER_THREAD` by`concurrency * 32`.

This value is a trade-off:
- Smaller is better as it gives more responsiveness to server changes (prio/throughput changes, new tests).
- But we need to reduce the waste from the stub-effect (ie. unused threads as we reach the end of a chunk).

The result of this trade-off should (all else equal) be proportional to the concurrency value.

For single threaded tests, concurrency = threads, and it means:
- Andrew 32 threads: 1024
- WorkerPool 16 threads: 512
- lucasart 7: 224

For 8 threaded tests, concurrency = int(threads / 8), so we have:
- Andrew 32 threads, concurrency 4: 128
- WorkerPool 16 threads, concurrency 2: 64
- lucasart 7: cannot play 8 threaded tests (concurrency = 0)

**Comment by lucasart** [comment]
Also, I'd set `REPORT_RATE = concurrency`, for 2 reasons:
* to avoid throwing away any game, when `GAMES_PER_THREAD` is not divisible by `REPORT_RATE`.
* to make the reporting loop take the same time (on avg / all esle equal) across machines.

**Comment by AndyGrant** [comment]
All good suggestions. I will do exactly as you have proposed, once I get the time.
