### ISSUE TITLE
recalibrate NPS

### ISSUE THREAD

**Issue by lucasart** [AndyGrant/OpenBench#43]
Weiss is running at 3.1 on WorkerPool 16 threads, and 2.9 on Andrew 32 threads. So a more reasonable value would be 3m, instead of the current 4m (which inflates tc by 33%).

Might be worth checking other engines while at it. I reckon both Ethereal and Demolito should use 1.4m, as for Laser, I don't know, but 625k looks low.

**Comment by TerjeKir** [comment]
Agreed, Weiss should probably be recalibrated as it has slowed down a bit since it was first added.

**Comment by lucasart** [comment]
Yes, I use bench-pext for Weiss, and pext for Ethereal. The big win for Demolito (8% speed-up) is CC=clang, on top of pext (2% speed-up). Only for Intel (haswell+) of course, for AMD pext should not be used (it's much slower than magics!).
```
CUSTOM_SETTINGS = {
    'ETHEREAL' : { 'path' : '/src/', 'args' : ['pext'] },
    'LASER'    : { 'path' : '/src/', 'args' : [] },
    'WEISS'    : { 'path' : '/src/', 'args' : ['bench-pext'] },
    'DEMOLITO' : { 'path' : '/src/', 'args' : ['CC=clang', 'pext'] },
};
```

**Comment by AndyGrant** [comment]
I'm going to do the following to determine NPS values for Ethereal and the others. This is the process I will take from now on to add any engines to the framework.

Run a set of 32 concurrency benches for Ethereal on my Ryzen 1950x Ubuntu box. My Ryzen box was ~1.00 ratio for Stockfish the last time I was putting the machine on Fishtest. Whatever that NPS value is for Ethereal, will be THE benchmark to compare other machines.

Supposing the Ethereal value is 1,450,000 nps. I will then run the same test set with each other engine, compiled NAIVELY (no clang for Demolito, no pext, just the _expected_ default worker compilation). And then produce the scalings. 

Technically, for Demolito (For example), this likely will result in a lower _effective_ time control. If that bothers you, I can change your default TC for STC/LTC/STCSMP/LTCSMP as you wish. The same applies for all others, but Laser is now defunct, and Weiss author is just happy to be here :)

I will put that script for test generation into the main dir of the OpenBench repo.

**Comment by lucasart** [comment]
Thanks Andy. That's fine, no need to adjust tc. Hopefully I'll find a way to speed-up gcc compile one day.

There is a problem with machine id registration. All the WorkerPool ones have been kicked it seems, and I just experienced the same issue. By running the old client I could get the machine registration done (machine.txt number updated with a new nb given by the server), and now running the new client succrssfully. Would be nice to replicate this machine regidstration part in the new client.

**Comment by AndyGrant** [comment]
| Engine   | Speed   | Benchmarking Output               |
|----------|---------|-----------------------------------|
| Ethereal | 1276136 | https://pastebin.com/raw/hi602xtb |
| Laser    | 709433  | https://pastebin.com/raw/HRTXFCqL |
| Weiss    | 2666967 | https://pastebin.com/raw/YLjuHeaP |
| Demolito | 1242999 | https://pastebin.com/raw/zCTjVFs6 |
