### ISSUE TITLE
Add support for RubiChess

### ISSUE THREAD

**Issue by AndyGrant** [AndyGrant/OpenBench#44]
Start of support thread for RubiChess

**Comment by AndyGrant** [comment]
Benchmarking Test : https://pastebin.com/raw/At7sZ6Pd
Speed will be 1,010,000 Nodes Per Second.
Scaled to a 32-thread test on a Ryzen 1950x Ubuntu box with g++ 7.4.0

**Comment by AndyGrant** [comment]
Issue for Windows workers compiling under GCC/G++

``RubiChess.h`` assumes that if the machine has ``__WIN32`` defined, then it is compiling under MSVC, where ``__popcnt64()`` is defined. 

The following change fixes the issue.
```
-#define POPCOUNT(x) (int)(__popcnt64(x))
+#define POPCOUNT(x) (int)(__builtin_popcountll(x))
```

**Comment by AndyGrant** [comment]
Issue for (at least) Linux workers

When a task is aborted, whether it be for completion, deletion, or being stopped, the Client is signaled to kill its current workload, which includes shutting down all copies of RubiChess. However, it appears that only half the engines are killed when this happens. The other half remain at 100% CPU utilization.

**Comment by Matthies** [comment]
Latest master should have fixed these issues. Thanks for the patch.

**Comment by AndyGrant** [comment]
I think things are good to go now. Only snag is that I need to make sure that Noobpwnftw has updated his client, since your output exposed a bug in my parsing.

**Comment by Matthies** [comment]
If it's just the order of output when collecting from stdout and stderr: I have changed RubiChess now to use only stdout for the 'bench" parameter (while my old parameter '-bench' still uses stderr for the table).

**Comment by AndyGrant** [comment]
Think its fair that this issue be closed now? Thanks for supporting the Framework.
