### ISSUE TITLE
invalid bench?

### ISSUE THREAD

**Issue by lucasart** [AndyGrant/OpenBench#49]
@AndyGrant: your machine stopped this test http://chess.grantnet.us/viewTest/4413/ due to invalid bench. both gcc and clang compile fine, and give me the same bench. workerpool also didn't have problems, and he's using an old version of the client (and gcc). did you change the bench parsing logic again ?

Here are the last lines of Demolito's output:
```
seal  : 11c28f6d2b272522
time  : 7353ms
nodes : 12681936
nps   : 1724729
```

**Comment by AndyGrant** [comment]
I'm an idiot and wiped my machine, but did not reinstall clang. Fixing now, and will reboot. Sorry for the issue.

**Comment by AndyGrant** [comment]
Fixed my machine; test is now running on my machine as expected.

**Comment by lucasart** [comment]
thanks. no worries, we're all idiots :)
