### ISSUE TITLE
Search: Failed and Neutral flags are mixed up, engine names not showing

### ISSUE THREAD

**Issue by TerjeKir** [AndyGrant/OpenBench#52]
Filtering by failed gives yellows, while neutral gives red. Should be the other way around.

**Comment by AndyGrant** [comment]
Engine names no longer appear under the engine selection dropdrown

**Comment by AndyGrant** [comment]
Resolved https://github.com/AndyGrant/OpenBench/commit/684fd636ed5c7283bd15ae9368962f89da5e9d87 , to be updated on the live version shortly.
