### ISSUE TITLE
More details about irregular behavior of engines

### ISSUE THREAD

**Issue by TerjeKir** [AndyGrant/OpenBench#55]
Would be nice to know which of the dev and master crashed, timed out, or had wrong bench.

**Comment by AndyGrant** [comment]
What if I do the following: Create a method for workers to send status reports, which appear in the Event log. 

This can include when an engine outputs a wrong bench, when an engine crashes, when an engine timesout, when an engine plays an illegal move. It will report the name of the engine, as well as the type of error. 

In addition, I will do https://github.com/AndyGrant/OpenBench/issues/31 which will allow us to easily see when to check the event log for errors. Is this sufficient? Its a solution that does not force a Client update, something which I am a fan of, as noobpwn has been AWOL.

**Comment by AndyGrant** [comment]
This would also address https://github.com/AndyGrant/OpenBench/issues/29

**Comment by TerjeKir** [comment]
Sounds good to me.

**Comment by AndyGrant** [comment]
Resolved in https://github.com/AndyGrant/OpenBench/commit/0c8ee1c54e1ae002b8f9665353d4634237f71e24
