### ISSUE TITLE
auto-registration does not work

### ISSUE THREAD

**Issue by jdart1** [AndyGrant/OpenBench#56]
If you start up a client on a machine that is not registered, you get a message like:
<Warning> Machine unregistered, will register with Server

but in fact, no registration happens. Looking at the code (OpenBench.py), machineid is set to 'None' in this case, and then the client waits for a workload. But there won't be a workload for a machine named 'None,' and so it apparently just keeps waiting.  It does not return "Bad Machine" (line 452).

**Comment by AndyGrant** [comment]
Try using Client.py. I am in the process of transitioning to a new client, which allows far greater utility, and will soon allow for additional reporting.
