### ISSUE TITLE
Double events

### ISSUE THREAD

**Issue by TerjeKir** [AndyGrant/OpenBench#59]
Looks like one can double approve a test:

https://i.imgur.com/Yjl5uRv.png

I see this is probably a resurrected bug #20

**Comment by AndyGrant** [comment]
I added this back sort of intentionally. I honestly don't mind the double events. Its (odd) for a single usual to double approve, but its whatever. If you open the webpage of an already approved test, it wont offer you an approve option. That is enough for me.
