### ISSUE TITLE
NPS NODES parsing

### ISSUE THREAD

**Issue by tryingsomestuff** [AndyGrant/OpenBench#72]
putting line uppercase can lead to error if engine is outputting also classic UCI or xboard ouput
```
bench1 = re.search(r'[0-9]+ NODES', line.upper())
```
This kind of output
```
info  depth 6 score cp 236 time 1 nodes 345 nps 344999
```
will match that but is NOT the expected output of "bench" command if this one is in fact running multiple positions.

**Comment by AndyGrant** [comment]
Is this a hypothetical problem, or an observered one? The client back tracks through the output looking for a matching line. Once it finds one, it stops looking.

```
    # Split the output line by line and look backwards
    for line in output.decode('ascii').strip().split('\n')[::-1]:
```

If this is an observe problem, it stems from the following:

```

        # Launch the engine and run a benchmark
        pathway = addExtension(os.path.join('Engines', engine).rstrip('/'))
        stdout, stderr = subprocess.Popen(
            './{0} bench'.format(pathway).split(),
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        ).communicate()

        # Parse output streams for the benchmark data
        bench, speed = parseStreamOutput(stdout)
        if bench is None or speed is None:
            bench, speed = parseStreamOutput(stderr)
        outqueue.put((int(bench), int(speed)))
```

note that the ``stdout`` is viewed first, followed by ``stderr``. A solution would to be to modify the following in the Popen command ``stderr=subprocess.STDIN,``, and drop ``stderr`` related code.

Although in my purview, bench output should not be reported to stderr.

**Comment by tryingsomestuff** [comment]
Yes this happens with Minic. For 2 reasons :
- Minic outputs bench to stderr
- Minic outputs classic UCI info string when searching even for "bench" command.

**Comment by AndyGrant** [comment]
Then the following would fix it, and also maintain correctness with the rest of the OpenBench engines, I believe.

```
        # Launch the engine and run a benchmark
        pathway = addExtension(os.path.join('Engines', engine).rstrip('/'))
        stdout, _= subprocess.Popen(
            './{0} bench'.format(pathway).split(),
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
        ).communicate()

        # Parse output streams for the benchmark data
        bench, speed = parseStreamOutput(stdout)
        outqueue.put((int(bench), int(speed)))
```

**Comment by tryingsomestuff** [comment]
I may have missed that for some engines, using the nps and nodes values of classic UCI is the way to answer openbench test command (I thought it was a name collision at first), this is why you are looping through streams backward.
That would mean all other engines are using a single position for this benchmark (or not resetting counter between search ?). 

I can also go with only 1 position for Minic ...

**Comment by AndyGrant** [comment]
Engines report a final result, which is a sum of the positions searched. Stockfish and Ethereal search a few dozen positions, and report a total node count and speed

**Comment by tryingsomestuff** [comment]
ok then the issue is reporting classic output to stdout and bench command to stderr inside Minic. If I output everything to stdout, it will be fine I guess as the last thing outputed will be the bench results.
