### ISSUE TITLE
Network path from relativeNetworkPath

### ISSUE THREAD

**Issue by tryingsomestuff** [AndyGrant/OpenBench#89]
If pathway is defined as `pathway = pathjoin('tmp/{0}/'.format(unzipname), data['test']['build']['path'])`
and 'path' from database is '' (empty) or '.' or '/' or './', the number of '/' counted in pathway inside relativeNetworkPath will be off by 1 (1 more is counted). 
Is it a bug ? for instance maybe fixable with
`pathway = os.path.normpath(pathway) + '/'` inside `getEngine` or I am using it wrong ?

**Comment by AndyGrant** [comment]
Yup, you would be correct. I'm rewriting the client from scratch anyway though, and using proper ``os.path.join()`` for everything, so this will resolve itself long term. You can just modify your version locally to fix it for yourself in the meantime.

**Comment by ppigazzini** [comment]
> Yup, you would be correct. I'm rewriting the client from scratch anyway though, and using proper `os.path.join()` for everything, so this will resolve itself long term. You can just modify your version locally to fix it for yourself in the meantime.

With python >= 3.4 the standard library [pathlib](https://docs.python.org/3/library/pathlib.html) simplifies the path management.

OT: consider to use venv in Readme (and if I'm not wrong `requests` is required):
```bash
sudo apt update && sudo apt install -y python3 python3-venv git 
git clone https://github.com/AndyGrant/OpenBench
cd OpenBench
python3 -m venv env
env/bin/python3 -m pip install --upgrade pip setuptools wheel requests Django==3.0.5 django-htmlmin
env/bin/python3 manage.py makemigrations
env/bin/python3 manage.py migrate
env/bin/python3 manage.py migrate --run-syncdb
env/bin/python3 manage.py createsuperuser
env/bin/python3 manage.py runserver 127.0.0.1:8000
```
